### ISSUE TITLE
Latest tagged version produces an error when Go module mode is enabled

### ISSUE THREAD

**Issue by cagedmantis** [zoom-lib-golang/zoom-lib-golang#25]
I attempted to import "github.com/zoom-lib-golang/zoom-lib-golang"

As demonstrated at: https://play.golang.org/p/U79iwt7vaAh

It fails with:
```
go: finding module for package github.com/zoom-lib-golang/zoom-lib-golang
go: downloading github.com/zoom-lib-golang/zoom-lib-golang v1.0.0
go: github.com/zoom-lib-golang/zoom-lib-golang@v1.0.0: parsing go.mod:
	module declares its path as: github.com/himalayan-institute/zoom-lib-golang
	        but was required as: github.com/zoom-lib-golang/zoom-lib-golang
```

The import fails when Go module mode is enabled because the latest tagged version of the module has a different address than the current address: [v1.0.0](https://github.com/zoom-lib-golang/zoom-lib-golang/commit/da1c30585ae28c23bd28570ec2a070b0d557e237#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R1).

A solution would be to add a new tag with the address updated in the `go.mod` file.

**Comment by rafecolton** [comment]
Published a new version, please check back in ~1hr to see if this is fixed

**Comment by rafecolton** [comment]
There seems to be something cached on the golang playground, can you confirm if this now works correctly locally? I expect that it should.

**Comment by cagedmantis** [comment]
I believe you added the v2.0.0 tag. When you tag a package with a different major version you've got to change the [import path to reflect that](https://golang.org/ref/mod#module-path). I think tagging TIP with v1.0.1 would work without having the v2.0.0 tag.

**Comment by rafecolton** [comment]
I'm sorry, but I don't quite understand what you're saying or why it's not working on Go playground. I tagged it v2.0.0 because there are backwards incompatible changes from v1.0.0, so v1.0.1 would be semantically inaccurate. Additionally, the [module path in the `go.mod` file](https://github.com/zoom-lib-golang/zoom-lib-golang/blob/main/go.mod#L1) refers to the updated package path. 

I tried also adding a `retract v1.0.0` line to the current `go.mod` file. Not really sure what else to do here besides tagging it v1.0.1, which seems incorrect.

**Comment by rafecolton** [comment]
I updated the urls in the v1.0.0 tag and force updated the tag, and I also tagged that commit as v1.0.1, hopefully one of these things will do the trick.

**Comment by rafecolton** [comment]
Well now it's saying I need to run `go mod tidy`... that's progress, except that when I run that locally on any of the tags or `main`, it does not change anything

**Comment by jredl-va** [comment]
@rafecolton can you publish a new version? v1.0.2

When you force publish versions like this the go checksum db is violated and downstream consumers have issues like so:

```
	github.com/himalayan-institute/zoom-lib-golang@v1.0.0: verifying go.mod: checksum mismatch
	downloaded: h1:t3p44iNBETLiJzk0HTH42PumtcP3AHi+Pd/ZY0SPpng=
	sum.golang.org: h1:yO9Ob+in8Nn1EnyCoEPoCwD20L+5zD9OIgODUb4VdXM=
```

**Comment by jredl-va** [comment]
Bump

**Comment by rafecolton** [comment]
Just pushed a tag for v1.0.2 - please let me know if that resolves your issue (or reopen this ticket if it does not).

**Comment by jredl-va** [comment]
Thank you @rafecolton!
